apiVersion: v1
data:
  JWT_SECRET: ZWI3MWYxNjQwMTFiMzgxNWZmMTA3ZjdlODEzZGNlNzg4ZTk0MWZmMjVmM2ExYzM0YjIwNjc3Zjc2Y2U5NGFmZg==
kind: Secret
metadata:
  creationTimestamp: null
  name: chat-api-secret
  namespace: ai-workspace
