apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: chat-api-secret
  namespace: {{ .Values.namespace }}
data:
  JWT_SECRET: ZWI3MWYxNjQwMTFiMzgxNWZmMTA3ZjdlODEzZGNlNzg4ZTk0MWZmMjVmM2ExYzM0YjIwNjc3Zjc2Y2U5NGFmZg==
type: Opaque
